version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=tiempos_muertos
      - INFLUXDB_ADMIN_USER=David
      - INFLUXDB_ADMIN_PASSWORD=David09-09
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: always  # Agregado para reiniciar automáticamente

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Cambiar si es necesario
    depends_on:
      - influxdb
    restart: always  # Agregado para reiniciar automáticamente

volumes:
  influxdb_data:
  grafana_data:

